language: ruby

rvm: 2.0.0

branches:
  only:
    - master

postgres:
  adapter: postgresql
  database: test
  username: postgres

before_script:
  - "psql -c 'create database test;' -U postgres"
  - "cp config/database.yml.sample config/database.yml"
  - "cp config/secrets.yml.sample config/secrets.yml"
  - "bundle exec rake db:create db:migrate RAILS_ENV=test"

script:
  - bundle exec rake

