:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 8
:queues:
  - [default, 1]
  - [mailer, 1]
  - [uploads, 1]
staging:
  :concurrency: 2
production:
  :concurrency: 25
development:
  :concurrency: 2
